var sample = [];
var i = 0;
while (i < 3) {
  sample = sample.concat([
    'abandon',
    'abandoned',
    'ability',
    'able',
    'about',
    'Above',
    'abroad',
    'absence',
    'absent',
    'absolute',
    'absolutely',
    'absorb',
    'Abuse',
    'abuse',
    'academic',
    'accent',
    'accept',
    'acceptable',
    'access',
    'accident',
    'accidental',
    'accidentally',
    'accommodation',
    'accompany',
    'according to',
    'account',
    'account for',
    'accurate',
    'accurately',
    'accuse',
    'achieve',
    'achievement',
    'acid',
    'acknowledge',
    'A couple',
    'acquire',
    'across',
    'Act',
    'action',
    'active',
    'actively',
    'activity',
    'Actor',
    'actress',
    'Actual',
    'actually',
    'ad',
    'adapt',
    'add',
    'addition',
    'additional',
    'add on',
    'address',
    'add up',
    'add up to',
    'adequate',
    'adequately',
    'adjust',
    'admiration',
    'admire',
    'admit',
    'adopt',
    'adult',
    'advance',
    'advanced',
    'advantage',
    'adventure',
    'advert',
    'advertise',
    'advertisement',
    'advertising',
    'advice',
    'advise',
    'affair',
    'affect',
    'affection',
    'Afford',
    'afraid',
    'after',
    'Afternoon',
    'afterwards',
    'again',
    'against',
    'age',
    'aged',
    'agency',
    'agent',
    'aggressive',
    'ago',
    'agree',
    'agreement',
    'Ahead',
    'aid',
    'aim',
    'air',
    'aircraft',
    'airport',
    'alarm',
    'Alarmed'
  ]);
  i++;
}

exports.strings_sample = sample;
